// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_ALL_ALERTS = 'REMOVE_ALL_ALERTS';

// Auth
export const AUTH_MODE = 'AUTH_STATE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Loaders
export const SET_BACKDROP_LOADER = 'SET_BACKDROP_LOADER';
export const RESET_BACKDROP_LOADER = 'RESET_BACKDROP_LOADER';
export const ADD_BACKDROP_LOADER_MESSAGE = 'ADD_BACKDROP_LOADER_MESSAGE';
export const SET_LOCAL_LOADER = 'SET_LOCAL_LOADER';
export const REMOVE_LOCAL_LOADER = 'REMOVE_LOCAL_LOADER';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';

// Mode
export const INIT_MODES = 'INIT_MODES';
export const SET_ACTIVE_MODE = 'SET_ACTIVE_MODE';
export const SET_MODE_META = 'SET_MODE_META';
export const DESTROY_MODE = 'DESTROY_MODE';
